# Generated by Django 3.1.8 on 2022-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('start_date', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
