# Generated by Django 3.1.8 on 2022-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasave',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
