# Generated by Django 3.1.8 on 2022-05-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daba_app', '0002_auto_20220519_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasave',
            name='start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
