# Generated by Django 3.1.8 on 2022-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daba_app', '0003_auto_20220519_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasave',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='datasave',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
